name: e_learning
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  flutter_otp_text_field: ^1.5.1+1

  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.1
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0
  get_it: ^8.0.0
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  dartz: ^0.10.1
  another_flushbar: ^1.12.30
  easy_localization: ^3.0.8
  carousel_slider: ^5.1.1
  video_player: ^2.8.4
  chewie: ^1.7.0
  lottie: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  percent_indicator: ^4.2.5
  skeletonizer: ^1.4.3
  flutter_lorem: ^2.0.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/vectors/
    - assets/images/png/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
flutter_assets:
  assets_path: assets/
  output_path: lib/constant/
  filename: assets.dart
  field_prefix: resource
  ignore_comments: true